service: my-lambda-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: us-east-2

functions:
  myFunction:
    handler: src.app.lambda_handler
    events:
      - http:
          path: hello
          method: get
